function Get-Records {
    param (
        [Parameter(Mandatory)]
        [String]
        $setName,

        [Parameter(Mandatory)]
        [String]
        $query
    )

    $uri = $baseURI + $setName + $query

    # Header for GET operations that have annotations
    $getHeaders = $baseHeaders.Clone()
    $getHeaders.Add('If-None-Match', $null)
    $getHeaders.Add('Prefer', 'odata.include-annotations="*"')

    $RetrieveMultipleRequest = @{
        Uri     = $uri
        Method  = 'Get'
        Headers = $getHeaders
    }

    Invoke-RestMethod @RetrieveMultipleRequest
}

function New-Record {
    param (
        [Parameter(Mandatory)]
        [String]
        $setName,

        [Parameter(Mandatory)]
        [hashtable]
        $body
    )

    $postHeaders = $baseHeaders.Clone()

    $CreateRequest = @{
        Uri     = $baseURI + $setName
        Method  = 'Post'
        Headers = $postHeaders
        Body    = ConvertTo-Json $body
    }

    Invoke-RestMethod @CreateRequest -ResponseHeadersVariable rh | Out-Null
    $url = $rh['OData-EntityId']
    $selectedString = Select-String -InputObject $url -Pattern '(?<=\().*?(?=\))'
    return [System.Guid]::New($selectedString.Matches.Value.ToString())
}

function Get-Record {
    param (
        [Parameter(Mandatory)]
        [String]
        $setName,

        [Parameter(Mandatory)]
        [Guid]
        $id,

        [String]
        $query
    )

    $uri = $baseURI + $setName
    $uri = $uri + '(' + $id.Guid + ')' + $query

    $getHeaders = $baseHeaders.Clone()
    $getHeaders.Add('If-None-Match', $null)
    $getHeaders.Add('Prefer', 'odata.include-annotations="*"')

    $RetrieveRequest = @{
        Uri     = $uri
        Method  = 'Get'
        Headers = $getHeaders
    }

    Invoke-RestMethod @RetrieveRequest
}

function Update-Record {
    param (
        [Parameter(Mandatory)]
        [String]
        $setName,

        [Parameter(Mandatory)]
        [Guid]
        $id,

        [Parameter(Mandatory)]
        [hashtable]
        $body
    )

    $uri = $baseURI + $setName
    $uri = $uri + '(' + $id.Guid + ')'

    # Header for Update operations
    $updateHeaders = $baseHeaders.Clone()
    $updateHeaders.Add('If-Match', '*') # Prevent Create

    $UpdateRequest = @{
        Uri     = $uri
        Method  = 'Patch'
        Headers = $updateHeaders
        Body    = ConvertTo-Json $body
    }

    Invoke-RestMethod @UpdateRequest
}

function Remove-Record {
    param (
        [Parameter(Mandatory)]
        [String]
        $setName,

        [Parameter(Mandatory)]
        [Guid]
        $id
    )

    $uri = $baseURI + $setName
    $uri = $uri + '(' + $id.Guid + ')'

    $DeleteRequest = @{
        Uri     = $uri
        Method  = 'Delete'
        Headers = $baseHeaders
    }

    Invoke-RestMethod @DeleteRequest
}
# SIG # Begin signature block
# MIInbQYJKoZIhvcNAQcCoIInXjCCJ1oCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDLNkvIQSKFWCJj
# 84DjcVtGi0tpUEm/jm6iFSWgzWXhC6CCDMkwggYEMIID7KADAgECAhMzAAACHPrN
# xZvoL37EAAAAAAIcMA0GCSqGSIb3DQEBCwUAMFcxCzAJBgNVBAYTAlVTMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBD
# b2RlIFNpZ25pbmcgUENBIDIwMjQwHhcNMjYwNDE2MTg1OTQxWhcNMjcwNDE1MTg1
# OTQxWjB0MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYD
# VQQDExVNaWNyb3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IB
# DwAwggEKAoIBAQDVsZfgOKmM31HPfoWOoNEiw0SlCiIxUMC0I9NMWbucKOw/e9lP
# oAoehQVu6SG65V4EPzrYsnBnFPNoi4/HoOdjhz1qkrEt4I6tEcxXU6oOeY9zGveC
# /3iBeuhLYxM3M/PkcUoebF+Nednm8OkdSPoDu8imViHPQq/8CQUu0WRR4rE+dMRf
# rpVqfmNi2qWCX94T4MsepijGVkwE//tJg0ryAiYdHT34LSnlG/RSBZmQRGWZ5g8j
# qnKjRParSqMft1gvjuUTVgtWNZfgcLFSK5Wa0myrq8OPcgTGGsRgun+tnSS+IxDT
# xVsAPH1OzvPjwomguByhUe/OcvUN0D5Wmp7xAgMBAAGjggGqMIIBpjAOBgNVHQ8B
# Af8EBAMCB4AwHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYBBQUHAwMwHQYDVR0O
# BBYEFNoH7a2YDjOSwpkp6DHcmUS7J+0yMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxFjAUBgNVBAUT
# DTIzMDAxMis1MDc1NjkwHwYDVR0jBBgwFoAUf1k/VCHarU/vBeXmo9ctBpQSCDEw
# YAYDVR0fBFkwVzBVoFOgUYZPaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9w
# cy9jcmwvTWljcm9zb2Z0JTIwQ29kZSUyMFNpZ25pbmclMjBQQ0ElMjAyMDI0LmNy
# bDBtBggrBgEFBQcBAQRhMF8wXQYIKwYBBQUHMAKGUWh0dHA6Ly93d3cubWljcm9z
# b2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwQ29kZSUyMFNpZ25pbmcl
# MjBQQ0ElMjAyMDI0LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IC
# AQAUnEqhaRXe0T3hIJjvdQErEkrA/7bByjn6t5IArODkkRjzkYwtKMc2yYj2quaN
# rLutWw2YZcngKPy1b71YyDJQTy4NDRwaSh9Tw5thrk3NmcPrAHia5vtcBJ1CgtKK
# 7mQbIcQ22d/N3813ayCDDFewu1+jsZmX+r/aTEqaOM4TVxVtRSkuCy8nAXKuChOK
# Li/zA4XuH8iEYqIsj2YoNaeSxVmeGiERXpKdo3dDmYi0kO5w2D8VS4c3+9h6gElY
# BaAAg/dYErBg27qT3vv0zRDJhJufvCNylA8S7/+8H5E/PV5cng6na9VV/w9OV3qu
# uND6zdGa2EX38Glp50F9AIQk3p2xXmcvorDeM4XJ7UlWYBi6g80J1SSOQnInCYFE
# msfUNn3+1AaTJKSJL83quKArTac2pKhu0Yzzzrzo6HrsRiQKzpnRBb1/dMa6P3hz
# 75XbMRBctNsFhZC07WCmjExdLg2eHW5uV0TY8D5+6wozJf7vF3+WHkYPO85Z+BC6
# U4FkNbYNycZ9cE4j1tXRdyDCfml6c0HWPHjNVDObrv9lKt3qUqFpX38VCqVCyNOO
# 1UcXfQiVjJw32U2WUKZjt/neJKHEBsm9kFsLuWzkQ53+qcaSaytmsCnk2gOglrlD
# 5d3kKyvvAw+rzm0lT8K38P6PLxfZQHhu4W8dV7Av8N2ZmDCCBr0wggSloAMCAQIC
# EzMAAAA5O7Y3Gb8GHWcAAAAAADkwDQYJKoZIhvcNAQEMBQAwgYgxCzAJBgNVBAYT
# AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBS
# b290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTI0MDgwODIwNTQxOFoX
# DTM2MDMyMjIyMTMwNFowVzELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQ
# Q0EgMjAyNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANgBnB7jOMeq
# lRYHNa265v4IY9fH8TKhemHfPINe1gpLaV3dhg324WwH06LcHbpnsBukCDNitryo
# 0dtS/EW6I/yEL/bLSY8hKpbfQuWusBPr9qazYcDxCW/qnjb5JsI1s8bNOg3bVATv
# QVL4tcf03aTycsz8QeCdM0l/yHRObJ9QqazM1r6VPEOJ7LL+uEEb73w6QCuhs89a
# 1uv1zerOYMnsneRRwCbpyW11IcggU0cRKDDq1pjVJzIbIF6+oiXXbReOsgeI8zu1
# FyQfK0fVkaya8SmVHQ/tOf23mZ4W9k0Ri22QW9p3UgSC5OUDktKxxcCmGL6tXLfO
# GSWHIIV4YrTJTT6PNty5REojHJuZHArkF9VnHTERWoTjAzfI3kP+5b4alUdhgAZ7
# ttOu1bVnXfHaqPYl2rPs20ji03LOVWsh/radgE17es5hL+t6lV0eVHrVhsssROWJ
# uz2MXMCt7iw7lFPG9LXKGjsmonn2gotGdHIuEg5JnJMJVmixd5LRlkmgYRZKzhxS
# CwyoGIq0PhaA7Y+VPct5pCHkijcIIDm0nlkK+0KyepolcqGm0T/GYQRMhHJlGOOm
# VQop36wUVUYklUy++vDWeEgEo4s7hxN6mIbf2MSIQ/iIfMZgJxC69oukMUXCrOC3
# SkE/xIkgpfl22MM1itkZ35nNXkMolU1lAgMBAAGjggFOMIIBSjAOBgNVHQ8BAf8E
# BAMCAYYwEAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYEFH9ZP1Qh2q1P7wXl5qPX
# LQaUEggxMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMA8GA1UdEwEB/wQFMAMB
# Af8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0fBFMwUTBP
# oE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMv
# TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRSMFAw
# TgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
# TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDANBgkqhkiG9w0BAQwFAAOC
# AgEAFJQfOChP7onn6fLIMKrSlN1WYKwDFgAddymOUO3FrM8d7B/W/iQ6DxXsDn7D
# 5W4wMwYeLystcEqfkjz4NURRgazyMu5yRzQh4LqjA4tStTcJh1opExo7nn5PuPBY
# nbu0+THSuVHTe0VTTPVhily/piFrDo3axQ9P4C+Ol5yet+2gTfekICS5xS+cYfSI
# vgn0JksVBVMYVI5QFu/qhnLhsEFEUzG8fvv0hjgkO+lkpV9ty6GkN4vdnd7ya6Q6
# aR9y34aiM1qmxaxBi6OUnyNl6fkuun/diTFnYDLTppOkr/mg5WSfCiDVMNCxtj4w
# PKC5OmHm1DQIt/MNokbbH3UGsFP1QbzsLocuSqLCvH09Io3fDPTmscR9Y75G4qX7
# RTX8AdBPo0I6OEojf39zuFZt0qOHm65YWQE69cZM2ueE1MB05dNNgHK9gTE7zKvK
# /fg8B2qjW88MT/WF5V5uvZGtqa9FSL2RazArA+rDPuf6JGYz4HpgMZHB4S6szWSK
# YBv0VisCzfxgeU+dquXW9bd0auYlOB58DPcOYKdc3Se94g+xL4pcEhbB54JOgAkw
# YTu/9dLeH2pDqeJZAABVDWRQCaXfO5LgyKwKCLYXpigrZYCjUSBcr+Ve8PFWMhVT
# Ql0v4q8J/AUmQN5W4n101cY2L4A7GTQG1h32HHAvfQESWP0xghn6MIIZ9gIBATBu
# MFcxCzAJBgNVBAYTAlVTMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# KDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMjQCEzMAAAIc
# +s3Fm+gvfsQAAAAAAhwwDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwG
# CisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZI
# hvcNAQkEMSIEIJmo032Uf17XDf1Pfi/noG/cg5PsqNkgScJTHI7oCDJhMEIGCisG
# AQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3
# Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEBBQAEggEAarpXPvWCTVm06C4399pX
# ZrVmg7Zjrfi04AVlzolgXD1J+bWO0w8RipVrv09io6R5ACpxjvwThr4CeBi73JRc
# b9xWe6+hmwCJR+cXYY/GRwUHVrxj0VyToykfLMAiqd3I/ODhuGwQtQLDFweI2Eke
# FN0h3FksA5IoWSiSJA6o2tmS+fH5bm1k+/tNbRRXNfbzWqNEVJeD3uv/RMOSIa7z
# ZwK3G4aXEImgxtUIspq8uO3kgtW8iMAphftoidRRVjUjLiP8b9mzAfCqQUhrDKx9
# kOtGCD8c/KsQBrrHDh+zcNwD+lgVTO4sbammx5N0oFRJsF8zliQQ15KEUdhjeZZh
# kKGCF6wwgheoBgorBgEEAYI3AwMBMYIXmDCCF5QGCSqGSIb3DQEHAqCCF4UwgheB
# AgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFZBgsqhkiG9w0BCRABBKCCAUgEggFEMIIB
# QAIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFlAwQCAQUABCChvSM4BXPCw8tU1HDI
# mMdf7gduX7FK2KPxV7dMlCsqEAIGajWRIHeEGBIyMDI2MDYyNDEwMTAzOC4xMVow
# BIACAfSggdmkgdYwgdMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRl
# ZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjUyMUEtMDVFMC1EOTQ3MSUwIwYD
# VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloIIR+zCCBygwggUQoAMC
# AQICEzMAAAIXcfsupa8BHeoAAQAAAhcwDQYJKoZIhvcNAQELBQAwfDELMAkGA1UE
# BhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAc
# BgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0
# IFRpbWUtU3RhbXAgUENBIDIwMTAwHhcNMjUwODE0MTg0ODIzWhcNMjYxMTEzMTg0
# ODIzWjCB0zELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
# BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsG
# A1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMScwJQYD
# VQQLEx5uU2hpZWxkIFRTUyBFU046NTIxQS0wNUUwLUQ5NDcxJTAjBgNVBAMTHE1p
# Y3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3DQEBAQUAA4IC
# DwAwggIKAoICAQDAzzawTD7f29hHuIYIgUOdg2FEz4HMXYBiKrl1SlmkkU9GMJyK
# lDpFRsj5EBg1ECkTHHnKCtdtpa27C+qyoBVJZtT9bp95y6OMguQ+qf2meC1ZGR9C
# BtiC9pcAuXo9jbI4f1/vYwP7oDLFB6dKkAx1TNj9CT+O2Owd0VdUF762yGUiRInc
# ZnDxVUqpODcZkSXO3BslY22uEES+F/pqfEx6BAwk/u07z8EnshOzj8BXcPZu/x4e
# TzVj586ZDyZDrVYurbAi2+XMhPlvN6Ur0u8TJx/nHWVfEDATDlrt2lL4IpNqeG2/
# 5DabB5sDJuN/2KjiTjyy1NqrWu1ys6IPB12pWbVL17yHVOzNcXOMsu8T0SaOc18h
# 7Cxj5EKFRoedjgUXDAkScS/8lLvqgdPSgZ3Lv4nrR8Y6XsDVShTICSGlvYGNr5LB
# IiIdtDgUPImIuVnp2tlnzgygnznYlLEzSEGMY7oVmU87yK43KTrzQOLxWdtI2kh0
# k34OGV6l5NQwEMeoKZ3SZVZFZk+bWm+C3L3dqw2382DqjibZ2eihY50zfIqwlpaP
# IeqJz2B9OtkEz48Jep5No7WgSJpD6HjDScdV1X5dK8jabXI3iKJuqObkc9oA7c4n
# 46Y0t+01WavhnpTZPqkhwsHKygpwNS8KrJxePgL/6fUoUGkMZ0MzD2Ca7wIDAQAB
# o4IBSTCCAUUwHQYDVR0OBBYEFFCs32OXA06h4TllCqcXnHxLVslDMB8GA1UdIwQY
# MBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBSoFCGTmh0dHA6
# Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29mdCUyMFRpbWUt
# U3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggrBgEFBQcBAQRgMF4wXAYIKwYB
# BQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY2VydHMvTWlj
# cm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0MAwGA1UdEwEB
# /wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwDgYDVR0PAQH/BAQDAgeAMA0G
# CSqGSIb3DQEBCwUAA4ICAQBGaAV2EHvEgAgcQSDkj/lL6DHrtpHpGJbxkDC0TebP
# yjR3Kf6kg/6WJ01HUgpBDSv5GNiAj1xnqZu8DK+Hd7ar8FXyuMcTe530/JjKrfZ6
# 4WB1ne9fhvlBd49aWkEBit3OJHbusfPpbCkfl1mxLKltcMFtCRaQ2XqDzbJPLcBs
# FsoNcF3PFmwRq5o6mVq0rsSvh2GCUoF7HwlDZ0xKRJnB4I0Nep32v/1bZV1FmwMk
# o/9dzhTJCVWxugGi0q1gRJcWSPBHUdWwf5DQLr383kI/9OrdiAjW5vhv37cwkUpa
# ElcJwkYVmRwvBSZjCgWDVcujsMsl0aOsgfWOwjY0VckVAd5/oB1F7URG9hB6q3Ks
# G/Ei9H4//zcU1jLPHTiKdRP1MXYDBM66oILpnrug3BHikQQnIAgRES+R2GON9ZyC
# yT+cZOV9qG81j9I4es1Eqjj0oOVxw3NEIlDJD4Pn2vv+p5s1LJA9N/Aj376MRjRD
# 9RYpU0uGKjnkZgGx4n32zs3OR3E6v1R+2nn3scSi9sDr2oaVnc6lQTcfVEEYNWn8
# W8za5dO6bwusyQ9fHkCn+Rs8BKwL2O72gwJ7YgRc7ZJ4PVoPciq8A50cUoeDW+ls
# 9RBJZvqDbF8FXfTAVypo9iDNxvE9Y/Jmor5LyXvPDrho7mGYnt5DCgx9O7RVrLqv
# jzCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkAAAAAABUwDQYJKoZIhvcNAQEL
# BQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNV
# BAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDEwMB4X
# DTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVowfDELMAkGA1UEBhMCVVMxEzAR
# BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
# Y3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3Rh
# bXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDk4aZM
# 57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX9gF/bErg4r25PhdgM/9cT8dm
# 95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1qUoNEt6aORmsHFPPFdvWGUNzB
# RMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8dq6z2Nr41JmTamDu6GnszrYBb
# fowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byNpOORj7I5LFGc6XBpDco2LXCO
# Mcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2krnopN6zL64NF50ZuyjLVwIYw
# XE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4dPf0gz3N9QZpGdc3EXzTdEonW
# /aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgSUei/BQOj0XOmTTd0lBw0gg/w
# EPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8QmguEOqEUUbi0b1qGFphAXPK
# Z6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6CmgyFdXzB0kZSU2LlQ+QuJYfM2
# BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzFER1y7435UsSFF5PAPBXbGjfH
# CBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQIDAQABo4IB3TCCAdkwEgYJKwYB
# BAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQUKqdS/mTEmr6CkTxGNSnPEP8v
# BO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMFwGA1UdIARVMFMwUQYM
# KwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0dHA6Ly93d3cubWljcm9zb2Z0
# LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0bTATBgNVHSUEDDAKBggrBgEF
# BQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBW
# BgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUH
# AQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtp
# L2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNydDANBgkqhkiG9w0BAQsF
# AAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwUtj5OR2R4sQaTlz0xM7U518Jx
# Nj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN3Zi6th542DYunKmCVgADsAW+
# iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU5HhTdSRXud2f8449xvNo32X2
# pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5KYnDvBewVIVCs/wMnosZiefw
# C2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGyqVvfSaN0DLzskYDSPeZKPmY7
# T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB62FD+CljdQDzHVG2dY3RILLFO
# Ry3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltEAY5aGZFrDZ+kKNxnGSgkujhL
# mm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFpAUR+fKFhbHP+CrvsQWY9af3L
# wUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcdFYmNcP7ntdAoGokLjzbaukz5
# m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRbatGePu1+oDEzfbzL6Xu/OHBE
# 0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQdVTNYs6FwZvKhggNWMIICPgIB
# ATCCAQGhgdmkgdYwgdMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRl
# ZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjUyMUEtMDVFMC1EOTQ3MSUwIwYD
# VQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoD
# FQBpsoAVoq3aFpR2qQd8VjMDN+BIy6CBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
# YW1wIFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA7eX+IDAiGA8yMDI2MDYyNDA2
# NTYzMloYDzIwMjYwNjI1MDY1NjMyWjB0MDoGCisGAQQBhFkKBAExLDAqMAoCBQDt
# 5f4gAgEAMAcCAQACAht1MAcCAQACAhRPMAoCBQDt50+gAgEAMDYGCisGAQQBhFkK
# BAIxKDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJ
# KoZIhvcNAQELBQADggEBACgldK8aw/0DK3UzaSjv9C5HcRAwYq4OmrtUfe+GFJOl
# 1JKrbU5hHkJLDu+4EV3p+cchJZhCNWFRV/1tFXMTJ0DibXQNg9jD2vlE4ewj3ekE
# 1Dn9DfqKUHuKVfqrh14gMoVUMefHoVbRO0eWExgsVNVYMMF+nTtBI4aVspK5oL+c
# ncxTZHvj/4MNiLAlUEXBLqFdfZi2+SS0SPdD1tzltbhVvwSX7ymnq1Cii53Tpu6y
# egikr+0+EvnONQkWS3PwWj5S6zR+0eWVIJjzRLXJHXDNqlY78DiMjJSyUoRhR56g
# 2a5IzDpXbk2xWIA6zfOgbEwI9jSdtMhMnU9bT4eOp4IxggQNMIIECQIBATCBkzB8
# MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
# bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1N
# aWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAhdx+y6lrwEd6gABAAAC
# FzANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEE
# MC8GCSqGSIb3DQEJBDEiBCBUgZMshdQGOiAZF4zOYkBZ63F7pPxMqmIzh1yegXC+
# rzCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EINDyUGA+XbfJnRLNRK3mmE4h
# 6Ac/LCuQ3B6/F7aT5FpbMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENB
# IDIwMTACEzMAAAIXcfsupa8BHeoAAQAAAhcwIgQgMwSJNDw7wbCxo7ZBzGSC4ok6
# nDcqvLouBXktWA2eTx4wDQYJKoZIhvcNAQELBQAEggIAdkr0RIKLK/WKS1Z/eJAl
# ajOicWtdNX+gRoARczmxkjS6f/GtMMrcbAfTVO0Zo3IiJ9oRVdNZfQ8KOGMbrDEs
# beqMsaZx9Hgc00cG17V7dOhJcXeBgFU9dvWlFaMsbYMcg2Vi6vuqCHAtC1BW0kzf
# pjqOxcbzLtXZIhHGVky7hn1OSDotm+VBTpJ4xhhRngUYAkEfB6Krdz7gUXoyrM/1
# S9MmgneqkdM0DckTg/uK7U/6cjjjPNFztoknXBoHXJBRieM8dm70etFZBMV7KipL
# 9ILrhzzB1XATCGFY7WN+YBfRm727DpvoAAAYchIzqY4quQqX26RSLOqfppRXZ+wn
# wMuLvu8cOtmX8Gbm+AyuSZWeWNznpOJsM5D/SUuiKhgZWvyoIhMu7OCGKHHHqqs4
# efzck4JQxw3suOE40Ix/9KTbQwlFHUt88CNSyXm6fRUGroMgdcePYRaZz71iMXdO
# LJuLfOLYxytNWMxnNXjkhnxVcoew2DT1y/CybeT/POv6DNnOeToV6QvbLJ9cF1pc
# KlKiX2ig6jyUbp8W5GDG44ths0UDwK0nUEMqZvkqgxjr512udivTRnxfaz9FmCVW
# 0pdTzRCnuJ9lu3ch98bEFMMdPlHVnijduU7lG8BpvdjDPq1TrMR+fdIN3mxLDYFN
# 68hH/nnLKDirLmPXY+ImSyY=
# SIG # End signature block
